name: 🕷 Wordfence crawler

on:
  schedule:
    - cron: '25 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Process vulnerabilities from Wordfence API (production)
        run: |
          python src/main.py --api_endpoint https://www.wordfence.com/api/intelligence/v2/vulnerabilities/production --tag production --overwrite --clean

      - name: Process vulnerabilities from Wordfence API (scanner)
        run: |
          python src/main.py --api_endpoint https://www.wordfence.com/api/intelligence/v2/vulnerabilities/scanner --tag candidate --overwrite

      - name: Commit new, updated and deleted templates individually with strict content checks
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure consistent diff behavior across platforms
          git config core.filemode false

          echo "Processing deleted YAML files (commit per file)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            git rm -q -- "$file" || true
            # Deletion is a content change by definition, but guard anyway
            if ! git diff --cached --quiet -- "$file"; then
              git commit -m "Deleted Nuclei template: $(basename "$file") 🤖"
            else
              git reset -q HEAD -- "$file" || true
            fi
          done < <(git ls-files --deleted | grep '\.yaml$' || true)

          echo "Processing new YAML files (commit per file, only if different from HEAD)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            # Stage and compare staged blob vs HEAD
            git add --intent-to-add -- "$file"
            git add -- "$file"
            if ! git diff --cached --quiet -- "$file"; then
              git commit -m "Added new Nuclei template: $(basename "$file") 🤖"
            else
              git reset -q HEAD -- "$file"
            fi
          done < <(git ls-files --others --exclude-standard | grep '\.yaml$' || true)

          echo "Processing modified YAML files (commit per file, only real content changes)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            git add -- "$file"
            if ! git diff --cached --quiet -- "$file"; then
              git commit -m "Updated Nuclei template: $(basename "$file") 🤖"
            else
              git reset -q HEAD -- "$file"
            fi
          done < <(git diff --name-only --diff-filter=M | grep '\.yaml$' || true)

      - name: Push all commits
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
